// aya-frontend/src/app/components/message/message.component.ts
import { Component, Input, OnInit } from '@angular/core';
import {
  animate,
  state,
  style,
  transition,
  trigger,
} from '@angular/animations';
import { DisplayMessage } from '../../interfaces/message';

@Component({
  selector: 'app-message',
  standalone: true,
  imports: [],
  templateUrl: 'message.component.html',

  styleUrl: 'message.component.css',
  animations: [
    trigger('push', [
      state(
        'init',
        style({
          height: '0px',
          opacity: 0,
        })
      ),
      state(
        'loaded',
        style({
          opacity: 1,
        })
      ),
      state(
        'removed',
        style({
          opacity: 0,
        })
      ),
      state(
        'deleted',
        style({
          height: '0px',
          opacity: 0,
        })
      ),
      transition('init => loaded', [animate('0.3s')]),
      transition('loaded => removed', [animate('0.3s')]),
      transition('loaded => deleted', [animate('0.3s 1s')]),
    ]),
  ],
})
export class MessageComponent implements OnInit {
  @Input() displayMsg: DisplayMessage | undefined;

  ngOnInit(): void {
    // IDK why but I put this in my legacy code
  }

  getIcon(): string {
    return this.displayMsg?.message.author.isBot ||
      this.displayMsg?.message.author.isAdmin
      ? this.displayMsg.message.author.isBot
        ? 'bi bi-gear'
        : 'bi bi-shield-fill-check'
      : '';
  }

  getSource(): string {
    switch (this.displayMsg?.message.source) {
      case 'discord':
        return '/discord.svg';
      case 'youtube':
        return '/youtube.svg';
      case 'twitch':
        return '/twitch.svg';
      default:
        return '/aya.svg';
    }
  }

  getState(): string {
    if (this.displayMsg?.init) return 'init';
    else if (this.displayMsg?.delete) return 'deleted';
    else if (this.displayMsg?.remove) return 'removed';
    else return 'loaded';
  }
}

@if (displayMsg) {
  <div class="row message-object" [@push]="getState()">

    <div class="col-1 message-source">
      <img [alt]="displayMsg.message.source" [src]="getSource()" class="message-source-svg">
    </div>

    <div class="col-4 author">
      <i style="color: silver" [class]="getIcon()"></i>
      <span [style.color]="displayMsg.message.author.color"><b> {{ displayMsg.message.author.username }}</b></span>
    </div>

    <div class="col-7">
      @if (!displayMsg.delete) {

        <div class="message">
          @if (displayMsg.edit) {
            <span><i>(edited) </i></span>
          }

          @for (msgPart of displayMsg.message.messageParts; track $index) {

            @if (msgPart.format) {
              <span [style.color]="msgPart.format.color"><b>{{ msgPart.content }}</b></span>
            } @else {
              <span>{{ msgPart.content }}</span>
            }

            @if (msgPart.emoji) {
              <img [alt]="msgPart.emoji.alt" [src]="msgPart.emoji.id" class="message-emoji"/>
            }

          }
        </div>
        <div class="attachment-container">
          @for (attachment of displayMsg.message.attachments; track $index) {
            <span class="attachment badge rounded-pill bg-secondary"><i
              class="bi bi-paperclip"></i>{{ attachment }}</span>
          }
        </div>
      } @else {
        <div class="message">
          <i>(deleted)</i>
        </div>
      }

    </div>
  </div>
} @else {

}

// aya-frontend/src/app/stream/[id]/MessageComponent.tsx
import React from "react";
import { DisplayMessage } from "@/models/message";
import messageComponentStyle from "./MessageComponent.module.css";
import Discord from "../../../../public/discord-icon.svg";
import Twitch from "../../../../public/twitch-icon.svg";
import Vercel from "../../../../public/vercel-icon.svg";
import { Icon } from "@blueprintjs/core";

export default function MessageComponent({
  display,
}: {
  display: DisplayMessage;
}) {
  if (!display.message) return null;

  const attachments = display.message.attachments.map((attachment, index) => (
    <span
      key={index}
      className={`${messageComponentStyle.attachment} badge rounded-pill bg-secondary`}
    >
      <i className="bi bi-paperclip"></i>
      {attachment}
    </span>
  ));

  const getIcon = () => {
    return display.message.author.isBot || display.message.author.isAdmin ? (
      display.message.author.isBot ? (
        <Icon icon="cog"></Icon>
      ) : (
        <Icon icon="shield"></Icon>
      )
    ) : (
      <Icon icon="user" style={{ margin: "5px" }}></Icon>
    );
  };

  const content = display.message.messageParts.map((msgPart, index) => {
    if (msgPart.format) {
      return (
        <span key={index} style={{ color: msgPart.format.color }}>
          <b>{msgPart.content}</b>
        </span>
      );
    }

    if (msgPart.emoji) {
      return (
        <img
          key={index}
          alt={msgPart.emoji.alt}
          src={msgPart.emoji.id}
          className={messageComponentStyle.emoji}
        />
      );
    }

    return <span key={index}>{msgPart.content}</span>;
  });

  return (
    <div
      className={`grid grid-cols-12 gap-2 ${messageComponentStyle.messageObject}`}
    >
      <div className="col-span-1">
        {display.message.source == "discord" && (
          <img
            alt={"d"}
            src={Discord.src}
            className={messageComponentStyle.icon}
          />
        )}
        {display.message.source == "twitch" && (
          <img
            alt={"d"}
            src={Twitch.src}
            className={messageComponentStyle.icon}
          />
        )}
        {display.message.source == "test_source" && (
          <img
            alt={"d"}
            src={Vercel.src}
            className={messageComponentStyle.icon}
          />
        )}
      </div>
      <div className={`col-span-1`}>{getIcon()}</div>
      <div className={`col-span-3 ${messageComponentStyle.author}`}>
        <span style={{ color: display.message.author.color }}>
          <b>{display.message.author.username}</b>
        </span>
      </div>
      <div className="col-span-7">
        {!display.delete && (
          <>
            {/*<div className={messageComponentStyle.attachmentContainer}>*/}
            {/*  {attachments}*/}
            {/*</div>*/}
            <div className={messageComponentStyle.message}>
              {display.edit && <i>(edited)</i>}
              {content}
            </div>
          </>
        )}
        {display.delete && (
          <div className={messageComponentStyle.message}>
            <i>(deleted)</i>
          </div>
        )}
      </div>
    </div>
  );
}
